server:
  port: 8080
spring:
  application:
    name: tickiting-project-rest
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: Misir1028
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      transport:
        protocol: smtp
      smtp:
        starttls:
          enabled: true
          required: true
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
    username: company.email@gmail.com
    password: company@2020
security:
  jwt:
    secret-key: company
springdoc:
  swagger-ui:
    path: /swagger-ui.html


